### ISSUE TITLE
Repetitive Code

### ISSUE THREAD

**Issue by DanBesu** [pauladam2001/Sem3_AdvancedProgrammingMethods#1]
https://github.com/pauladam2001/Sem3_AdvancedProgrammingMethods/blob/5f24e6e11df8670bacbc87a30221f3c8ef7d1a81/ToyLanguageInterpreter/src/model/statement/VariableDeclarationStatement.java#L29
I was studing your code base and got into this issue: 
this line of code could be use just once and you will get rid of the ifs and the repetitive concern of checking the types will be gone.

**Comment by pauladam2001** [comment]
Yes, Dan, you are right. Thanks a lot!
