### ISSUE TITLE
Problems with Error Exceptions

### ISSUE THREAD

**Issue by DanBesu** [pauladam2001/Sem3_AdvancedProgrammingMethods#2]
https://github.com/pauladam2001/Sem3_AdvancedProgrammingMethods/blob/058d2fa10deb87f0627eeaf1f119663da059192d/ToyLanguageInterpreter/src/model/expression/RelationalExpression.java#L65

You must be careful when printing the error message referring to the InterfaceType the user uses. You are checking for IntType() objects, but the error message alerts the user that he did not introduce a Booltype, which is not the case in this kind of Expression.

**Comment by pauladam2001** [comment]
Right, thank you!
